config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'weddings', to: 'users/registrations#new_wedding'
    post 'weddings', to: 'users/registrations#create_wedding'
    root to: "devise/registrations#new"
  end

  resources :users do
    resources :posts, only: [:new, :create, :destroy]
    resources :communities, only: [:index, :create, :destroy]
    resources :weddings, only: [:index, :edit, :update, :show]
    resources :albums, only: [:index, :create]
  end

  
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many_attached :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :wedding
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :wedding
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :wedding
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags, dependent: :destroy
end

app/models/post_form.rb
class PostForm
  include ActiveModel::Model

  attr_accessor :attendance, :name, :name_kana, :category_gloom, :category_bride, :address, :mail, :departure, :go_home, :message, :wedding_id,
                :tag_name, :post_id,
                :tag_id
  
  with_options presence: true do
    validates :attendance
    validates :name
    validates :name_kana
    validates :address
    validates :mail
    validates :message
    validates :wedding_id
    validates :tag_name
  end

  def save(tag_list)
    post = Post.create(attendance: attendance, name: name, name_kana: name_kana, category_gloom: category_gloom, category_bride: category_bride, address: address, mail: mail, departure: departure,
      go_home: go_home, message: message, wedding_id: wedding_id)
    
    tag_list.each do |tag_name|
      tag = Tag.where(tag_name: tag_name).first_or_initialize
      tag.save
      PostTag.create(post_id: post.id, tag_id: tag.id)
    end
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :wedding
  has_one :post
  has_many :albums
end

app/models/wedding.rb
class Wedding < ApplicationRecord
  belongs_to :user, optional: true
  has_many :posts
  has_many :communities
  has_many :chats
  validates :gloom_name, :bride_name, :gloom_name_en, :bride_name_en, :date, :answer_date, :message, :location, :url, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @wedding = @user.wedding
    @album = Album.new
    @albums = @user.albums
    if @albums != nil
      @images = []
      @albums.each do |album|
        all_images = album.images
        all_images.each do |image|
          @images.push(image)
        end
      end
    end
  end

  def create
    @user = User.find(params[:user_id])
    @album = Album.new(album_params)
    if @album.save
      redirect_to user_albums_path(@user.id)
    else
      render :index
    end
  end

  private
  def album_params
    params.require(:album).permit(images: []).merge(user_id: @user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    user_weddings_path(current_user.id) # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    new_user_session_path # ログアウト後に遷移するpathを設定
  end
  
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @community = Community.new
    @wedding = @user.wedding
    @communities = @wedding.communities
  end

  def create
    @user = User.find(params[:user_id])
    @community = Community.new(community_params)
    @community.save
    @wedding = @user.wedding
    @communities = @wedding.communities
  end

  def destroy
    @user = User.find(params[:user_id])
    @wedding = @user.wedding
    @community = Community.find(params[:id])
    @community.destroy
    @communities = @wedding.communities
  end

  private
  def community_params
    params.require(:community).permit(:community_name).merge(wedding_id: @user.wedding.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  

  def new
    @user = User.find(params[:user_id])
    @post_form = PostForm.new
    @wedding = @user.wedding
    @communities = @wedding.communities
  end

  def create
    @user = User.find(params[:user_id])
    @wedding = @user.wedding
    @communities = @wedding.communities
    # インスタンス生成
    @post_form = PostForm.new(post_form_params)
    tag_list = params[:post_form][:tag_name].split(",")
    # 新規登録
    if @post_form.valid?
      @post_form.save(tag_list)
      redirect_to controller: :weddings, action: :index, user_id: @user.id
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @wedding = @user.wedding
    @post = Post.find(params[:user_id])
    @post.destroy
    redirect_to controller: :weddings, action: :show, user_id: @user.id, id: @wedding.id
  end

  

  private
  def post_form_params
    params.require(:post_form).permit(:attendance, :name, :name_kana, :category_gloom, :category_bride, :address, :mail, :departure,
                                      :go_home, :message, :tag_name).merge(wedding_id: @user.wedding.id)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/weddings_controller.rb
class WeddingsController < ApplicationController
  def index
    @wedding = Wedding.find_by(user_id: params[:user_id])
    @user = @wedding.user
    @communities = @wedding.communities
    @post_form = PostForm.new
  end
  
  def edit
    @user = User.find(params[:user_id])
    @wedding = @user.wedding
  end

  def update
    @user = User.find(params[:user_id])
    @wedding = @user.wedding
    if @wedding.valid?
      @wedding.update(wedding_params)
      redirect_to user_weddings_path(@user.id)
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:user_id])
    @wedding = Wedding.find(params[:id])
    @posts = @wedding.posts
  end

  private
 
  def wedding_params
    params.require(:wedding).permit(:gloom_name, :bride_name, :gloom_name_en, :bride_name_en, :date, :answer_date, :message, :message_info, :location, :url, :address, :reception_time, :wedding_time, :photo_time, :party_time, :bye_time, :second_party_time)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/views/posts/_new.html.erb
<div id="post_new">
<h2>招待状の回答</h2>

<%= form_with model:post_form, url: user_posts_path(user_id: user.id), remote: true do |f| %>
  <%#= render "devise/shared/error_messages", resource: @post %>

  <div class="field">
    <%= f.radio_button :attendance, :attend %>
    <%= f.label :attendance, "出席", {value: :attend, style: "display: inline-block;"} %>
    <%= f.radio_button :attendance, :absence %>
    <%= f.label :attendance, "欠席", {value: :absence, style: "display: inline-block;"} %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :name_kana %><br />
    <%= f.text_field :name_kana %>
  </div>

  <div class="field">
    <%= f.check_box 'category_gloom', {:checked => false}, true, false %>
    <%= f.label :category_gloom, "新郎", {value: :true, style: "display: inline-block;"} %>
    <%= f.check_box 'category_bride', {:checked => false}, true, false %>
    <%= f.label :category_bride, "新婦", {value: :true, style: "display: inline-block;"} %>
  </div>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :mail %><br />
    <%= f.text_field :mail %>
  </div>

  <div class="field">
    <%= f.label :departure %><br />
    <%= f.date_field :departure %>
  </div>

  <div class="field">
    <%= f.label :go_home %><br />
    <%= f.date_field :go_home %>
  </div>

  <div class="field">
    <%= f.label :tag_name %><br/>下記より参加希望のグループを選択し、記入してください<br />
    <%= f.text_field :tag_name, placeholder:",で区切ってください" %>
  </div>
  <div>
    <% communities.each do |community| %>
    <ul>
      <li>
        <%= community.community_name %>
      </li>
    </ul>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>

  <div class="actions">
    <%= f.submit "回答する" %>
  </div>

<% end %>
<div id="new-back">
<%= link_to "戻る", user_weddings_path(user.id), remote: true %>
</div>

</div>

app/views/posts/_sidebar.html.erb
<% if user_signed_in? %>
  <div class="logout"><%= link_to "ログアウト", destroy_user_session_path, method: :DELETE %></div>
  <div class="logout"><%= link_to "式情報編集", edit_user_wedding_path(user.id, wedding.id) %></div>
<% else %>
  <div class="login"><%= link_to "ログイン", new_user_session_path %></div>
<% end %>
<div class="menu-list">
  <ul>
    <% if user_signed_in? %>
      <li>出欠管理</li>
    <% end %>
    <li>アルバム</li>
    <li>チャットルーム</li>
  </ul>
</div>

app/views/posts/new.html.erb
<div id="post_new">
<%= link_to "戻る", user_weddings_path(@user.id) %>

<%= form_with model:@post_form, url: user_posts_path(user_id: @user.id), local: true do |f| %>
  <%#= render "devise/shared/error_messages", resource: @post %>

  出欠
  <div class="field select">
    <%= f.radio_button :attendance, :attend %>
    <%= f.label :attendance, "出席", {value: :attend, style: "display: inline-block;"} %>
    <%= f.radio_button :attendance, :absence %>
    <%= f.label :attendance, "欠席", {value: :absence, style: "display: inline-block;"} %>
  </div>

  <div class="field">
    名前<br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    名前(カタカナ)<br />
    <%= f.text_field :name_kana %>
  </div>

  招待分類<br/>
  <div class="field select">
    <%= f.check_box 'category_gloom', {:checked => false}, true, false %>
    <%= f.label :category_gloom, "新郎", {value: :true, style: "display: inline-block;"} %>
    <%= f.check_box 'category_bride', {:checked => false}, true, false %>
    <%= f.label :category_bride, "新婦", {value: :true, style: "display: inline-block;"} %>
  </div>

  <div class="field">
    住所<br />
    <%= f.text_field :address %>
  </div>

  <div class="field">
    メールアドレス<br />
    <%= f.text_field :mail %>
  </div>

  <div class="field">
    出発日<br />
    <%= f.date_field :departure %>
  </div>

  <div class="field">
    帰宅日<br />
    <%= f.date_field :go_home %>
  </div>

  <div class="field">
    メッセージ<br />
    <%= f.text_field :message %>
  </div>

  <div class="field">
    下記よりコミュニティーを選択してください<br />
    <div class="all-community">
      / <% @communities.each do |community| %>
          <%= community.community_name %> /
      <% end %>
    </div><br/>
    <%= f.text_field :tag_name, placeholder:",で区切ってください" %>
  </div>

  <div class="actions">
    <%= f.submit "回答する" %>
  </div>

<% end %>

</div>