config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'weddings', to: 'users/registrations#new_wedding'
    post 'weddings', to: 'users/registrations#create_wedding'
    root to: "devise/registrations#new"
  end

  resources :users do
    resources :posts, only: [:new, :create, :destroy]
    resources :communities, only: [:index, :create, :destroy]
    resources :weddings, only: [:index, :edit, :update, :show]
    resources :albums, only: [:index, :create]
  end

  
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many_attached :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :wedding
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :wedding
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :wedding
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags, dependent: :destroy
end

app/models/post_form.rb
class PostForm
  include ActiveModel::Model

  attr_accessor :attendance, :name, :name_kana, :category_gloom, :category_bride, :address, :mail, :departure, :go_home, :message, :wedding_id,
                :tag_name, :post_id,
                :tag_id
  
  with_options presence: true do
    validates :attendance
    validates :name
    validates :name_kana
    validates :address
    validates :mail
    validates :message
    validates :wedding_id
    validates :tag_name
  end

  def save(tag_list)
    post = Post.create(attendance: attendance, name: name, name_kana: name_kana, category_gloom: category_gloom, category_bride: category_bride, address: address, mail: mail, departure: departure,
      go_home: go_home, message: message, wedding_id: wedding_id)
    
    tag_list.each do |tag_name|
      tag = Tag.where(tag_name: tag_name).first_or_initialize
      tag.save
      PostTag.create(post_id: post.id, tag_id: tag.id)
    end
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :wedding
  has_one :post
  has_many :albums
end

app/models/wedding.rb
class Wedding < ApplicationRecord
  belongs_to :user, optional: true
  has_many :posts
  has_many :communities
  has_many :chats
  validates :gloom_name, :bride_name, :gloom_name_en, :bride_name_en, :date, :answer_date, :message, :location, :url, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @wedding = @user.wedding
    @album = Album.new
    @albums = @user.albums
    if @albums != nil
      @images = []
      @albums.each do |album|
        all_images = album.images
        all_images.each do |image|
          @images.push(image)
        end
      end
    end
  end

  def create
    @user = User.find(params[:user_id])
    @album = Album.new(album_params)
    if @album.save
      redirect_to user_albums_path(@user.id)
    else
      render :index
    end
  end

  private
  def album_params
    params.require(:album).permit(images: []).merge(user_id: @user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    user_weddings_path(current_user.id) # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    new_user_session_path # ログアウト後に遷移するpathを設定
  end
  
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @community = Community.new
    @wedding = @user.wedding
    @communities = @wedding.communities
  end

  def create
    @user = User.find(params[:user_id])
    @community = Community.new(community_params)
    @community.save
    @wedding = @user.wedding
    @communities = @wedding.communities
  end

  def destroy
    @user = User.find(params[:user_id])
    @wedding = @user.wedding
    @community = Community.find(params[:id])
    @community.destroy
    @communities = @wedding.communities
  end

  private
  def community_params
    params.require(:community).permit(:community_name).merge(wedding_id: @user.wedding.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  

  def new
    @user = User.find(params[:user_id])
    @post_form = PostForm.new
    @wedding = @user.wedding
    @communities = @wedding.communities
  end

  def create
    @user = User.find(params[:user_id])
    @wedding = @user.wedding
    @communities = @wedding.communities
    # インスタンス生成
    @post_form = PostForm.new(post_form_params)
    tag_list = params[:post_form][:tag_name].split(",")
    # 新規登録
    if @post_form.valid?
      @post_form.save(tag_list)
      redirect_to controller: :weddings, action: :index, user_id: @user.id
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @wedding = @user.wedding
    @post = Post.find(params[:user_id])
    @post.destroy
    redirect_to controller: :weddings, action: :show, user_id: @user.id, id: @wedding.id
  end

  

  private
  def post_form_params
    params.require(:post_form).permit(:attendance, :name, :name_kana, :category_gloom, :category_bride, :address, :mail, :departure,
                                      :go_home, :message, :tag_name).merge(wedding_id: @user.wedding.id)
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/weddings_controller.rb
class WeddingsController < ApplicationController
  def index
    @wedding = Wedding.find_by(user_id: params[:user_id])
    @user = @wedding.user
    @communities = @wedding.communities
    @post_form = PostForm.new
  end
  
  def edit
    @user = User.find(params[:user_id])
    @wedding = @user.wedding
  end

  def update
    @user = User.find(params[:user_id])
    @wedding = @user.wedding
    if @wedding.valid?
      @wedding.update(wedding_params)
      redirect_to user_weddings_path(@user.id)
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:user_id])
    @wedding = Wedding.find(params[:id])
    @posts = @wedding.posts
  end

  private
 
  def wedding_params
    params.require(:wedding).permit(:gloom_name, :bride_name, :gloom_name_en, :bride_name_en, :date, :answer_date, :message, :message_info, :location, :url, :address, :reception_time, :wedding_time, :photo_time, :party_time, :bye_time, :second_party_time)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/views/albums/index.html.erb
<div class="hamburger-menu">
  <input type="checkbox" id="menu-btn-check">
  <label for="menu-btn-check" class="menu-btn"><span></span></label>
  <!--ここからメニュー-->
  <div class="menu-content">
    <%= render partial: "weddings/sidebar", locals: { wedding: @wedding, user: @user } %>
  </div>
  <!--ここまでメニュー-->
</div>

<div class="wedding-story">
    <div class="message">
      <h1>WEDDING　MEMORIES</h1>
      <h3><%= @wedding.gloom_name_en %> & <%= @wedding.bride_name_en %></h3>
      <h3><%= @wedding.date %></h3>
      <p>私たちのパーティーに参加してくださりありがとうございました</P>
      <p>皆様との写真を共有させていただきます</P>
    </div>
</div>

<% if user_signed_in? %>
<div class="photo-form">
<%= form_with model: @album, url: user_albums_path(@user.id), local: true do |f| %>

  <div class="click-upload">
    <%= f.file_field :images, multiple: true %>
  </div>
  <div class="actions">
    <%= f.submit "登録" %>
  </div>
<% end %>
</div>
<% end %>

<% if @albums != nil %>
<div class="photos">
  <% @images.each do |image| %>
    <%= image_tag(image, width:200) %>
  <% end %>
</div>
<% end %>

<%= link_to "戻る", user_weddings_path(@user.id) %>

app/views/communities/_community.html.erb
  <% communities.each do |community| %>
    <div>
    <%= community.community_name %>
    <%= link_to "[削除]", user_community_path(community.wedding.user.id, community.id), method: :delete, remote: true %>
    </div>
  <% end %>

app/views/communities/create.js.erb
$('#community_lists').html("<%= j (render partial: "community", locals: { communities: @communities }) %>");
$("input").val('');

app/views/communities/destroy.js.erb
$('#community_lists').html("<%= j (render partial: "community", locals: { communities: @communities }) %>");

app/views/communities/index.html.erb
<div class="community">
<h1>コミュニティー登録</h1>
コミュニティーを設定すると、本アプリを通してゲスト同士で連絡を取り合うことができます</br>
（ゲストの出欠回答時にコミュニティーを選んでもらう）

<div class="community-content">
<%= form_with model: @community, url: user_communities_path(@user.id), remote: true do |f| %>

  <div>
    コミュニティー名<br />
    <%= f.text_field :community_name, placeholder:"新郎大学" %>
  </div>
  <div class="actions">
    <%= f.submit "登録" %>
  </div>
<% end %>
  
<div id="community_lists">
  <%= render partial: "community", locals: { communities: @communities } %>
</div>

<%= link_to "マイページへ", user_weddings_path(@user.id) %>
</div>

app/views/weddings/_sidebar.html.erb
<% if user_signed_in? %>
  <div class="logout"><%= link_to "ログアウト", destroy_user_session_path, method: :DELETE %>
  <%= link_to "式情報編集", edit_user_wedding_path(user.id, wedding.id) %></div>
<% else %>
  <div class="logout"><%= link_to "ログイン", new_user_session_path %></div>
<% end %>
<div class="menu-lists">
  <ul>
    <li class="menu-list"><%= link_to "トップページ", user_weddings_path(user.id) %></li>
    <% if user_signed_in? %>
      <li class="menu-list"><%= link_to "出欠管理", user_wedding_path(user.id, wedding.id) %></li>
    <% end %>
    <li class="menu-list"><%= link_to "アルバム", user_albums_path(user.id) %></li>
    <li class="menu-list"><%= link_to "チャットルーム", "#" %></li>
  </ul>
</div>

app/views/weddings/_table.html.erb
<table border="1" bordercolor="gray" width="100%" cellpadding="20" id="sampleTable">
  <tr>
    <th>出欠
    <select id="sampleSelect" onChange="goFilter();">
      <option value="all">全て</option>
      <option value="attend">出席</option>
      <option value="absence">欠席</option>
    </select>
    </th>
    <th>名前</th>
    <th>ナマエ</th>
    <th>新郎側</th>
    <th>新婦側</th>
    <th>住所</th>
    <th>email</th>
    <th>到着日</th>
    <th>帰宅日</th>
    <th>メッセージ</th>
    <th>コミュニティ</th>
    <th>削除</th>
  </tr>
  <% posts.each do |post| %>
    <tr>
    <td><%= post.attendance %></td>
    <td><%= post.name %></td>
    <td><%= post.name_kana %></td>
    <td><%= post.category_gloom %></td>
    <td><%= post.category_bride %></td>
    <td><%= post.address %></td>
    <td><%= post.mail %></td>
    <td><%= post.departure %></td>
    <td><%= post.go_home %></td>
    <td><%= post.message %></td>
    <td>
      <% post.tags.each do |tag| %>
        <%= tag.tag_name %>
      <% end %>
    </td>
    <td><%= link_to '削除', user_post_path(@user.id, post.id), method: :delete, class: "destroy" %></td>
    </tr>
  <% end %>
</table>

    
<!-- 【 CSS 】 ---------------------------------------------- -->
<style type="text/css">
  #sampleTable  th                {border : 1px solid #666;}
  #sampleTable  td                {border : 1px solid #666;}
  .allNoDisplay tr:not(.colTitle) {display: none;}
  .fruit        tr[fruit]         {display: table-row;}
  .vegetable    tr[vegetable]     {display: table-row;}
  .meat         tr[meat]          {display: table-row;}
</style>

<!-- 【 JavaScript 】 -------------------------------------- -->
<script type="text/javascript">
function goFilter(){
  var wTable = document.getElementById("sampleTable");
  var wSelect = document.getElementById("sampleSelect");
  var value  = wSelect.options[wSelect.selectedIndex ].value;
  if(value == 'all'){
    // --- 全ての場合はクラスをクリア ---
    wTable.className = '';
  }else{
    // --- タイトル以外のTRを非表示＋指定属性を持つTRのみ表示 ---
    wTable.className = 'allNoDisplay ' + value;
  }
}
</script>

<!-- 【 HTML 】 ------------------------------------------- -->
<table style="width:300px;" id="sampleTable">
  <tr class="colTitle">
    <th>No</th>
    <th>
        <select id="sampleSelect" onChange="goFilter();">
          <option value="all">全て</option>
          <option value="fruit">くだもの</option>
          <option value="vegetable">野菜</option>
          <option value="meat">肉</option>
        </select>
    </th>
    <th>金額</th></tr>
  <tr fruit><td>1</td><td>りんご</td><td>500円</td></tr>
  <tr vegetable><td>2</td><td>レタス</td><td>298円</td></tr>
  <tr meat><td>3</td><td>鶏肉</td><td>249円</td></tr>
  <tr fruit><td>4</td><td>みかん</td><td>398円</td></tr>
  <tr vegetable><td>5</td><td>キャベツ</td><td>198円</td></tr>
  <tr meat><td>6</td><td>牛肉</td><td>560円</td></tr>
  <tr meat><td>7</td><td>豚肉</td><td>318円</td></tr>
  <tr vegetable fruit><td>8</td><td>トマト</td><td>198円</td></tr>
</table>

app/views/weddings/edit.html.erb
<h1>
  Wedding情報編集</br>
  <%= link_to "コミュニティー編集はこちらから", user_communities_path(@user.id) %></br>
  <%= link_to "戻る", user_weddings_path(@user.id) %>
</h1>

<div class="wedding-registration">
<%= form_with model: @wedding, url: user_wedding_path(@user.id, @wedding.id), local: true do |f| %>
  <%#= render "devise/shared/error_messages", resource: @wedding %>

  <h2>お二人について教えてください</h2>
  <div class="field">
    新郎 名前<br />
    <%= f.text_field :gloom_name %>
  </div>

  <div class="field">
    新婦 名前<br />
    <%= f.text_field :bride_name %>
  </div>

  <div class="field">
    新郎 名前(ローマ字)<br />
    <%= f.text_field :gloom_name_en %>
  </div>

  <div class="field">
    新婦 名前(ローマ字)<br />
    <%= f.text_field :bride_name_en %>
  </div>

  <div class="field">
    挙式日<br />
    <%= f.text_field :date %>
  </div>

  <div class="field">
    ゲスト回答期限<br />
    <%= f.text_field :answer_date %>
  </div>

  <div class="field">
    ゲストへのメッセージ<br />
    <%= f.text_field :message %>
  </div>

  <h2>挙式会場について教えてください</h2>

  <div class="field">
    名前<br />
    <%= f.text_field :location %>
  </div>

  <div class="field">
    ホームページURL<br />
    <%= f.text_field :url %>
  </div>

  <div class="field">
    住所<br />
    <%= f.text_field :address %>
  </div>

  <div class="field">
    挙式会場に関するメッセージ<br />
    <%= f.text_field :message_info %>
  </div>

  <h2>タイムスケジュールについて教えてください</h2>
  <div class="field">
    受付時間<br />
    <%= f.text_field :reception_time %>
  </div>

  <div class="field">
    挙式開始時間<br />
    <%= f.text_field :wedding_time %>
  </div>

  <div class="field">
    写真撮影開始時間<br />
    <%= f.text_field :photo_time %>
  </div>

  <div class="field">
    パーティー開始時間<br />
    <%= f.text_field :party_time %>
  </div>

  <div class="field">
    パーティー終了時間<br />
    <%= f.text_field :bye_time %>
  </div>

  <div class="field">
    2次会開始時間<br />
    <%= f.text_field :second_party_time %>
  </div>

  <div class="actions">
    <%= f.submit "更新" %>
  </div>
<% end %>
</div>

app/views/weddings/index.html.erb
<!--header>
  <div>
    <div class="images">
      <div class="image"><%= link_to image_tag("093F920C-B714-4056-B2E7-8E813CCB30D8.jpeg", size: '400x400') %></div>
      <div class="image"><%= link_to image_tag("IMG_0160.jpeg", size: '400x400') %></div>
      <div class="image"><%= link_to image_tag("IMG_0170.jpeg", size: '400x400') %></div>
    </div>
  </div>
</header-->

<div class="hamburger-menu">
  <input type="checkbox" id="menu-btn-check">
  <label for="menu-btn-check" class="menu-btn"><span></span></label>
  <!--ここからメニュー-->
  <div class="menu-content">
    <%= render partial: "sidebar", locals: { wedding: @wedding, user: @user } %>
  </div>
  <!--ここまでメニュー-->
</div>

<div class= main>

  <div class="invitation">
    <div class="message">
      <h1>WEDDING<br>INVITATION</h1>
      <h3><%= @wedding.gloom_name_en %> & <%= @wedding.bride_name_en %></h3>
      <h3><%= @wedding.date %></h3>
      <p>皆様　いかがお過ごしでしょうか</P>
      <p>さて　このたび　私たちは結婚することとなりました</P>
      <p>つきましては　ご挨拶を兼ねて</P>
      <p>ささやかなパーティーを催したいと思います</P>
      <p>この日が皆様にとって楽しい一日になれば幸いです</P>
    </div>
  </div>

  <div class="time">
    <h1>COUNT DOWN</h1>
    <div id="countdownArea" class="countdown">
      <span id="countdown-day"></span>DAYS<br>
      <span id="countdown-hour"></span>HOURS
      <span id="countdown-min"></span>MINUTES
      <span id="countdown-sec"></span>SECONDS
    </div>
  </div>

  <div class="info-content">
    <div class="schedule">
      <h1 class="schedule-title">Wedding Time Line</h1>
      <div class="schedule-lists">
        <div class="schedule-list">
          <%= link_to image_tag("te5.png") %>
          <p>受付<br><%= @wedding.reception_time.strftime("%H:%M") %></p>
        </div>
        <div class="schedule-list">
          <%= link_to image_tag("tent-1024x1024.png") %>
          <p>挙式<br><%= @wedding.wedding_time.strftime("%H:%M") %></p>
        </div>
        <div class="schedule-list">
          <%= link_to image_tag("camera.png") %>
          <p>集合写真<br><%= @wedding.photo_time.strftime("%H:%M") %></p>
        </div>
        <div class="schedule-list">
          <%= link_to image_tag("cutlery.png") %>
          <p>披露宴<br><%= @wedding.party_time.strftime("%H:%M") %></p>
        </div>
        <div class="schedule-list">
          <%= link_to image_tag("kirakira.png") %>
          <p>お見送り<br><%= @wedding.bye_time.strftime("%H:%M") %></p>
        </div>
        <div class="schedule-list">
          <%= link_to image_tag("crown-1024x1024.png") %>
          <p>二次会<br><%= @wedding.second_party_time.strftime("%H:%M") %></p>
        </div>
      </div>
      <div class="self-message">
        <p><%= @wedding.message %></p>
      </div>
    </div>
    <div class="hr"><hr class="schedule-information"></div>
    <div class="information">
      <div class="map">
        map
      </div>
      <div class="info-message">
        <h2><%= @wedding.location %></h2>
        <p><%= @wedding.address %></p>
        <a href="<%= @wedding.url %>"><%= @wedding.url %></a>
        <div class="self-message">
          <p><%= @wedding.message_info %></p>
        </div>
      </div>
    </div>
  </div>

  <div class="answer">
    <div class="answer-content">
    <div class="answer-message">
      <p>お手数ではございますが</P>
      <p>12月31日までにご返信くださいますよう</P>
      <p>お願い申し上げます</P>
      <p></P>
    </div>
    <div class="answer-btn"><%= link_to "招待状に回答する", new_user_post_path(user_id: @user.id) %></div>
    </div>
  </div>
</div>

app/views/weddings/show.html.erb
<div class="show">

  <div class="hamburger-menu">
  <input type="checkbox" id="menu-btn-check">
  <label for="menu-btn-check" class="menu-btn"><span></span></label>
  <!--ここからメニュー-->
  <div class="menu-content">
    <%= render partial: "sidebar", locals: { wedding: @wedding, user: @user } %>
  </div>
  <!--ここまでメニュー-->
  </div>

  <div class="show-guests">
    <%= render partial: "table", locals: { posts: @posts } %>
  </div>
  <%= link_to "戻る", user_weddings_path(@user.id) %>

</div>